version: 0.0
os: linux
files:
   - source: /
     destination: /opt/files
permissions:
   - object: /opt/files
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/install_sssd.sh
      runas: root
   AfterInstall:
    - location: scripts/setup_ssh.sh
      runas: root
