version: 0.0
os: linux
files:
   - source: /
     destination: /opt/devops-tools
permissions:
   - object: /opt/devops-tools
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/zabbix-install-agent.sh
      runas: root
    - location: scripts/zabbix-delete-host.sh
      runas: root
   AfterInstall:
    - location: scripts/zabbix-setup-init.sh
      runas: root
